---
name: Molecule Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro: [ 'centos7', 'centos8', 'ubuntu1804, 'ubuntu2004', 'ubuntu2010', 'ubuntu2104' ]
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3
        users: actions/setup-python@v1
        with:
          - python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install molecule docker
      - name: Run Molecule tests
        run: |
          molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}